version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: djangodemo
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: djangopass
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
